#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning log.*"
rm log.*
echo "Cleaning processor*"
rm -r processor*
echo "Cleaning postProcessing"
rm -rf postProcessing
echo "Cleaning 0/"
find ./0/ -not -name "p.orig" -and -not -name "T.orig" -and -not -name "U.orig" -and -not -name "Ydefault.orig" -type f -delete
echo "Cleaning time directories (numerical folders) but keeping 0/"
for dir in [0-9]*; do
    if [ "$dir" != "0" ]; then
        rm -rf "$dir"
    fi
done
echo "Cleaning constant/polyMesh/"
rm -r constant/polyMesh
echo "Cleaning system/"
rm -r system/sampleConfigDict system/setFieldsDict